#!/bin/bash
case $1 in
	check|cleanup|install|pristine|rdoc|uninstall|update|which)
		every_ruby -S gem $@
		for file in $RUBY_PATH/1.*/bin/*; do
			add_ruby_command `basename $file`
		done
		;;
	*)
		if [ $@ = "server" ]; then
			gem server --daemon
		else
		  PATH=$RUBY_PATH/$RUBY_VERSION/bin:$PATH exec $RUBY_PATH/$RUBY_VERSION/bin/gem $@
		fi
		;;
esac